### PR TITLE
Added support for PgSQL client SSL certificates and for DropDatabase

### PR DESCRIPTION
**Pull request by petrce**
Added support for client SSL certificates (used by e.g. Google Cloud SQL) and added support for DropDatabase

### CODE REVIEW

**Comment by petrce** [comment]
hmm, need to find a way how to add certificates without changing the API :/ any ideas?

**Comment by sabeersulaiman** [comment]
@petrce Can we pass this down as a configuration ?

**Comment by droyad** [comment]
You can add overloads instead of adding parameters to existing methods. That'll keep the API compatible.

**Comment by knunery** [comment]
@droyad  I would like to add drop database functionality for postgres. Should I go ahead and make a new PR?

**Comment by sungam3r** [comment]
@petrce Please rebase onto `master` if you are still interested.

**Comment by droyad** [comment]
This was enabled via https://github.com/DbUp/dbup-postgresql/pull/16

**Pull request closed without merging**
