### PR TITLE
Patches SqlClient security vulnerability

### PR DESCRIPTION
**Pull request by brunosansigolo**
A [security vulnerability](https://github.com/advisories/GHSA-8g2p-5pqh-5jmc) was made public on 08/11/2022 by Microsoft on GitHub affecting the NuGet packages Microsoft.Data.SqlClient (<= 1.1.3 and >= 2.0.0, < 2.1.2) and System.Data.SqlClient (<= 4.8.4).

This PR updates all the references to their patched version.

### CODE REVIEW

**Review by AdrianJSClark — APPROVED** [review]
Thanks for this. Appreciate the change.

**Comment by AdrianJSClark** [comment]
Seems there are some issues with the main branch building that I've fixed in #655. Until that merges you should be able to explicitly install the patched release of `System.Data.SqlClient` in your project to have it override the version we reference here.

**Comment by AdrianJSClark** [comment]
The build only failed because PRs don't have permissions to push packages & test results etc.

**Comment by brunosansigolo** [comment]
> The build only failed because PRs don't have permissions to push packages & test results etc.

Awesome, thank you Adrian!

**Pull request merged**
