### PR TITLE
Cleanup samples csprojs

### PR DESCRIPTION
**Pull request by sungam3r**

### CODE REVIEW

**Comment by sungam3r** [comment]
@AdrianJSClark @droyad Could you please review? Changes are really obvious.

**Comment by sungam3r** [comment]
Rel: #404

**Comment by sungam3r** [comment]
Hi, @mjauernig. Nice to meet a new member here. Honestly I almost forgot about my own PRs here. There are chances that I can do a review from time to time but as I said in email - no big activity here from me.

**Comment by mjauernig** [comment]
At the beginning it would help, if you can review my pull requests. On the other pull requests i will take a look. Thank you.

**Pull request merged**
