### PR TITLE
Add Readme into packages + csprojs cleanup

### LINKED ISSUE #663: NuGet Packages Missing a "ReadMe"
NuGet.org recommends that packages include a README, which the DbUp packages currently do not.

Documentation here: https://learn.microsoft.com/en-au/nuget/nuget-org/package-readme-on-nuget-org

### PR DESCRIPTION
**Pull request by sungam3r**
fixes #663

### CODE REVIEW

**Comment by sungam3r** [comment]
@AdrianJSClark could you please review?

**Comment by sungam3r** [comment]
Rel: #404

**Comment by sungam3r** [comment]
@mjauernig please review this one

**Review by mjauernig — APPROVED** [review]

**Comment by sungam3r** [comment]
@mjauernig Please use `squash and merge` option when merging PRs to keep commits history linear and clean. For now (using default `merge` option) comments are useless:
изображение

Example of repo where PRs are merged with `squash and merge` option:
изображение

**Comment by mjauernig** [comment]
Ok. Thank you for the hint.

**Pull request merged**
