### PR TITLE
Add support for drop database and implementation for SQL Server

### PR DESCRIPTION
**Pull request by dennisroche**
https://github.com/DbUp/DbUp/issues/220

Refactored `EnsureDatabase`, extracting the logic for getting the master connection string.

### CODE REVIEW

**Comment by JakeGinnivan** [comment]
Build fail :(

**Comment by dennisroche** [comment]
@JakeGinnivan, should we add support for the other database providers? I think `EnsureDatabase` only has support for SqlServer.

**Comment by dennisroche** [comment]
@JakeGinnivan Haha, Yeaaah. I didn't compile befor submitting the PR as I was late for work.

**Comment by dennisroche** [comment]
@JakeGinnivan tests failing, however not locally as https://github.com/DbUp/DbUp/blob/release/4.0.0/src/dbup-tests/ApiTests.cs#L1 has `#if !NETCORE`.

**Comment by droyad** [comment]
Oops, this closed when I deleted the `4.0.0` branch after merging it into `master`

**Comment by dennisroche** [comment]
Fixed the merge conflict. Thanks for picking up all these issues @droyad. 🥇

**Pull request merged**
