### PR TITLE
New VersionFoldersScriptProvider

### PR DESCRIPTION
**Pull request by rintje**
* Target new VersionFolderScriptsProvider to branch Release/4.0.0
Merged docs for VersionFoldersScriptProvider into docs/more-info/script-providers.md

### CODE REVIEW

**Comment by rintje** [comment]
Sorry for the mess. Having trouble creating a clean pull request, as the results of master->fork sync seems is somehow included in the PR. Please ignore all but the last commit.

**Comment by JakeGinnivan** [comment]
FYI the way you can fix this is:

```
git checkout -b VersionFolderScriptProvider
git fetch upstream
git rebase upstream/release/4.0.0 -i
```

This will start an interactive rebase. You simply then delete all the lines which correspond to commits you don't care about (so just leave your commit).

The rebase will then continue and you will have a fresh branch on top of release/4.0.0.

The other option is

```
# create a new branch based on the remote release/4.0.0 branch
git checkout -b NewVersionFolderScriptProvider upstream/release/4.0.0
git cherry-pick <shaofcommityouwant>
```

Then use git extensions (or another git tool) and cherry-pick the commit across to your new branch.

**Comment by JakeGinnivan** [comment]
Did this end up making it in somewhere?

**Comment by JakeGinnivan** [comment]
Hrrm, sorry about that. There is an open PR. On it

**Pull request closed without merging**
