### PR TITLE
Oracle support for DbUP

### PR DESCRIPTION
**Pull request by SimonRupar**
Based on pull-request #53 

Done: 
1. Added Oracle provider for DbUp. Because Oracle does not support roll-back transaction, all scripts have hash of content. More on pull-reqest #53 under point number 6.
2. Added console application for oracle. 
3. Added unit-tests for testing oracle support provider.

### CODE REVIEW

**Comment by SimonRupar** [comment]
@JakeGinnivan I have finished this pull-request. Tell me if you have some issues with any part of code.

**Comment by JakeGinnivan** [comment]
I have been away for the last few weeks and lead up to that was a bit busy. Should have some time in the next week or so as I get back into things

Sent from my Windows Phone
________________________________

**Comment by jnus** [comment]
What's the maturity of this implemetation? Ready for use?

**Comment by SimonRupar** [comment]
@jnus We are using it in order to deploy our project and so far have not have any issues with it. But this pull-request requires #63 to be included.

**Comment by JakeGinnivan** [comment]
Hey guys, I do have a working copy of this.

Since it was done things have changed, I am reworking these changes to use the new testing infrastructure and a few other things. Just ran out of time when I last attempted and the past month or so has been busy with speaking engagements.

If I don't get to it in the next few weeks I have time off over christmas which I will likely use to clear my backlog of PR's and maybe try and get v4 out.

**Comment by jnus** [comment]
Perfect! -  @JakeGinnivan  - do you have a branch with your progress?

**Comment by SimonRupar** [comment]
@JakeGinnivan - If you want I can also take a look into this.

**Comment by JakeGinnivan** [comment]
@SimonRupar if you could rebase this onto master, that would be great :)

**Comment by cletisgipson** [comment]
I would love to see DbUp support Oracle.  How do I pull this branch/pull request, so I can get Oracle Support.  

One thing, when I run a script to say create a trigger, i can not put the ; at the end of it.  Without this oracle does not think it is a valid command and throws an error.

Any suggestions?

**Comment by SimonRupar** [comment]
@cletisgipson, If I understand you correctly, you only need to fix logic for splitting statements. But we are using DevArt for splitting our statements and works for us. Maybe you can just do a custom provider which will handle you this scenario. 

@JakeGinnivan Yes I can do rebase of this solution to latest version and remove depenedcy from pull request #63 . I have already started to do it, I expect to be done by the end of this weekend.

**Comment by cletisgipson** [comment]
@SimonRupar, which edition of the devart tool are you using?  Does it allow you to put a semicolon at the end of your statements?

**Comment by SimonRupar** [comment]
@cletisgipson You can also try creating custom IScriptPreprocessor. I have created you a code snippet:

https://gist.github.com/SimonRupar/2d45d4433e1673d08d30#file-gistfile1-txt

**Comment by cletisgipson** [comment]
Thanks for the advice.

I implemented the DevartConnectionManager and I am having the same issue.

Here is my issue, everytime I run the DBUP program whether locally or remotely it does not give an error.  However, when I run locally the database takes the changes and my app works correctly.  Now when I run the same program remotely, the database does not take the changes.  When I view the object in SQL Developer it has a little red x by the name.  Why does the tool work properly on one machine but not on another?  When I run the tool, it is pointing to the same database and I make sure to clear out any changes before I run the tool.

Here is the script.

create or replace TRIGGER SEDD_HIST
       before
    update on CORPS_SPECIAL_ED_DIRECTOR
    for each row
          begin
          insert into CORPS_SPECIAL_ED_DIRECTOR_HIST (
               SPECIAL_ED_DIRECTOR_HIST_ID,
               SPECIAL_ED_DIRECTOR_ID,
               SEDD_CORP_ID_CHAR,
               SPECIAL_ED_DIRECTOR_TYPE,
               SEDD_AUTHROIZER_NAME,
               SEDD_PLANNING_DISTRICT_NAME,
               SEDD_TITLE,
               SEDD_NAME_FIRST,
               SEDD_NAME_MIDDLE,
               SEDD_NAME_LAST,
               SEDD_EMAIL,
               SEDD_PHONE,
               SEDD_FAX,
               SEDD_ADDRESS,
               SEDD_CITY,
               SEDD_STATE,
               SEDD_ZIP,
               SEDD_LAST_UPDATE,
               SELD_TITLE,
               SELD_NAME_FIRST,
               SELD_NAME_MIDDLE,
               SELD_NAME_LAST,
               SELD_EMAIL,
               SELD_PHONE,
               SELD_FAX,
               SELD_ADDRESS,
               SELD_CITY,
               SELD_STATE,
               SELD_ZIP,
               SELD_LAST_UPDATE )
       values ( CORPS_SPL_ED_DIRECTOR_HIST_SEQ.NEXTVAL,
               :old.SPECIAL_ED_DIRECTOR_ID,
               :old.SEDD_CORP_ID_CHAR,
               :old.SPECIAL_ED_DIRECTOR_TYPE,
               :old.SEDD_AUTHROIZER_NAME,
               :old.SEDD_PLANNING_DISTRICT_NAME,
               :old.SEDD_TITLE,
               :old.SEDD_NAME_FIRST,
               :old.SEDD_NAME_MIDDLE,
               :old.SEDD_NAME_LAST,
               :old.SEDD_EMAIL,
               :old.SEDD_PHONE,
               :old.SEDD_FAX,
               :old.SEDD_ADDRESS,
               :old.SEDD_CITY,
               :old.SEDD_STATE,
               :old.SEDD_ZIP,
               :old.SEDD_LAST_UPDATE,
               :old.SELD_TITLE,
               :old.SELD_NAME_FIRST,
               :old.SELD_NAME_MIDDLE,
               :old.SELD_NAME_LAST,
               :old.SELD_EMAIL,
               :old.SELD_PHONE,
               :old.SELD_FAX,
               :old.SELD_ADDRESS,
               :old.SELD_CITY,
               :old.SELD_STATE,
               :old.SELD_ZIP,
               sysdate );
       end;

**Comment by Kemyke** [comment]
Hey guys, can you give me a state of this issue. We are really looking forward to Oracle db support in one of our project. What do you think will this be included in the near future?

Thanks!

**Comment by JakeGinnivan** [comment]
I am trying to clear the backlog now.

First I am pulling SqlServer out of code, releasing 4.0.0-beta.1, then will pull oracle support in on top of that change. DbUp has not reached to top of my OSS todo list so hopefully a week or so.

**Comment by JakeGinnivan** [comment]
@SimonRupar I am trying to get this in, but it's really hard because these PR's have so many different concepts coming in at once.

Apart from the fact there is now merge hell, I think we need to split things apart and bring them in one by one. For instance, the script validation. So my initial question is:

What concepts are need to be introduced for Oracle support. I see the script validation, anything else?

**Comment by JakeGinnivan** [comment]
TBH, mysql also does implicit transaction commit for DDL changes. Either we make this a first class concept in DbUp (as a separate PR, before Oracle comes in) or we make it a docs issue and simply implement oracle like all other databases.

Which way do you think we should go?

**Comment by JakeGinnivan** [comment]
@SimonRupar also, if you do the oracle support on top of the release/4.0.0 branch. It should be pretty easy. It has been refactored further and SqlServer has been split out of core.

**Comment by SimonRupar** [comment]
@JakeGinnivan Sorry for late replies and unresponsiveness, but I am little busy with some personal stuff. 

I have also tried last week to rebase this to update with DbUp master branch. I can also try to rebase on release/4.0.0 brach. Bacause there changes make "mergin hell" as you mentioned, I have also started to remove additional concepts.

What I am saying, I totally agree with you. I will first try to make those changes for Oracle as minimal as possible, and then handle all additionall concepts if you want.  

Ok, let me firstly explained proposed concepts:
** - Script validation**: This is majorly used in development. Sometimes it is required to change scripts but we don't allow to change already applied changes to database. Also maybe you would like validation for already applied scripts. This is why we use hashing of already executed scripts (part of scripts).
**- Marking failing statement:** I have to mark where was the last point to which script was successfully executed. Because of implicit transaction commit on DDL. This enables me to execute scripts repetitively without to worry which part of script was executed. For instance you have scirpt 10.sql

CREATE TABLE table_name
(
column_name1 data_type(size),
);

/* !!!Typo!!!!/*
SLECT table_name

This script will fail for second statement, but first statement will be applied to database. This causes when you run this script again it skip first statement and start with second. 

**- Seperation of MSSQL part from DbUp ** Already in release/4.0.0?
- **ScriptContainer:** One location where all sql statement are written. Not really a concept but I like the idea of having all sql statement written on one location. This also makes DBA job easier and more maintainable. 

So I am planning to make this pull request for Oracle changes as minimal as possible. I will also rebase to release/4.0.0. Hopefully I will finish this in following days. Regarding other concepts, I'm open to suggestions. I will need concepts regarding script validation and marking failing statemant in our environment. I can also create seperate pull requests for those concepts.

**Comment by JakeGinnivan** [comment]
Gonna close this one out @SimonRupar 

Appreciate your efforts on this, hope you understand my push back on this PR. I can't give any meaningful feedback as too much has changed. Script validation is great, I would like that myself and I think it's the first step.
The marking of failing statements is interesting, mysql can benefit from this but makes things more complex. Could helpers to take exclusive lock, backup/restore if failed be an alternate option?

**Pull request closed without merging**
