### PR TITLE
dbup-postgresql: added support for NETStandard 1.3 and 2.0

### PR DESCRIPTION
**Pull request by justslon**
Multi-target dbup-postgresql for NETStandard 1.3, 2.0 and NET 3.5.

### CODE REVIEW

**Comment by jackjwilliams** [comment]
So close, is the hold up the Cake build? Are there any known workarounds?

**Comment by jackjwilliams** [comment]
I've pulled this PR down, the tests run fine in Visual Studio. It seems it may be something with Mono.Cecil (the out of memory exception that AppVeyor is throwing.

I've tracked the issue to https://github.com/nunit/nunit3-vs-adapter/issues/296

which led me to

https://github.com/jbevain/cecil/issues/282

**Comment by jackjwilliams** [comment]
Whatever PublicApiGenerator is, it was published by @JakeGinnivan, maybe he can shed some light. When updating to 6.1.0, it still throws errors. I gave it a try!

**Comment by droyad** [comment]
@justslon Thanks for the PR, and @jackjwilliams for trying it out. I've merged this. Also, yeh that test was a bit flakey, it's been rewritten :)

**Pull request merged**
