### PR TITLE
Update index.md add note about EnsureDatabase

### PR DESCRIPTION
**Pull request by LRPalacios**
Add a note in docs about EnsureDatabase method, in the index.md file

### CODE REVIEW

**Comment by LRPalacios** [comment]
i had to navigate trough the issues to find out about this helpful method, it will be great to have it on the docs!

**Comment by JakeGinnivan** [comment]
Hey, to update the docs just submit a PR to the /docs folder. Once merged the docs auto-deploy

**Comment by JakeGinnivan** [comment]
Thanks for the PR

**Comment by LRPalacios** [comment]
np, thanks for the awesome project

**Pull request merged**
