### PR TITLE
Target new VersionFoldersScriptsProvider to branch Release/4.0.0

### PR DESCRIPTION
**Pull request by rintje**
Merged readme.md docs for VersionFoldersScriptProvider into docs/more-info/script-providers.md

### CODE REVIEW

**Comment by rintje** [comment]
OK, finally got the git stuff sorted :-)

**Comment by JakeGinnivan** [comment]
I know this has been ages, but I wonder if we should separate the script provider and the script sorter. 

.ScriptsEmbeddedInAssembly(..)
.SortScriptsAlphanumerically() // .SortScriptsUsing<VersionFolderScriptSorter>()

Thoughts?

**Comment by rintje** [comment]
Sounds like a good idea. That makes room for additional sort types like SemVer.

The VersionFolderScriptProvider currently also filters scripts using the Version class, to omit scripts with a higher version than the version specified in param targetVersion. Thus, if sorting is made a separate functionality, then i guess filtering should also be separated? For example: FilterScriptsByVersionUsing()

**Comment by rintje** [comment]
note: see #231 first

**Pull request closed without merging**
