### PR TITLE
Issue #730 - Fixed cake local build.

### PR DESCRIPTION
**Pull request by Havagan**
Fixes issue #730.

- Updated cake.tool version.
- Excludes /tools/ folder via `.gitignore`.
- Cake downloads requires tools including `nuget.exe`.
- Added info output and null check for ENV `GITHUB_OUPUT`.
- Added `globa.json` to force .NET 7.0 tool support.

### CODE REVIEW

**Comment by mjauernig** [comment]
When i try to run the `build.ps1` script, it fails with the message:

```
SemVer:Version_Info:
{
  "Major": 5,
  "Minor": 0,
  "Patch": 38,
  "PreReleaseTag": "PullRequest0732.1",
  "PreReleaseTagWithDash": "-PullRequest0732.1",
  "PreReleaseLabel": "PullRequest0732",
  "PreReleaseLabelWithDash": "-PullRequest0732",
  "PreReleaseNumber": 1,
  "WeightedPreReleaseNumber": 30001,
  "BuildMetaData": null,
  "BuildMetaDataPadded": "",
  "FullBuildMetaData": "Branch.pr-732.Sha.bc361d9cd8d19d0b5fafda61133d7defb5e4936f",
  "MajorMinorPatch": "5.0.38",
  "SemVer": "5.0.38-PullRequest0732.1",
  "LegacySemVer": "5.0.38-PullRequest0732-1",
  "LegacySemVerPadded": "5.0.38-PullRequest0732-0001",
  "AssemblySemVer": "5.0.38.0",
  "AssemblySemFileVer": "5.0.38.0",
  "FullSemVer": "5.0.38-PullRequest0732.1",
  "InformationalVersion": "5.0.38-PullRequest0732.1+Branch.pr-732.Sha.bc361d9cd8d19d0b5fafda61133d7defb5e4936f",
  "BranchName": "pr/732",
  "EscapedBranchName": "pr-732",
  "Sha": "bc361d9cd8d19d0b5fafda61133d7defb5e4936f",
  "ShortSha": "bc361d9",
  "NuGetVersionV2": "5.0.38-pullrequest0732-0001",
  "NuGetVersion": "5.0.38-pullrequest0732-0001",
  "NuGetPreReleaseTagV2": "pullrequest0732-0001",
  "NuGetPreReleaseTag": "pullrequest0732-0001",
  "VersionSourceSha": "f7323634077328221ea9d24f0af66202f9c3180c",
  "CommitsSinceVersionSource": 1,
  "CommitsSinceVersionSourcePadded": "0001",
  "UncommittedChanges": 0,
  "CommitDate": "2023-09-04"
}
ENV:GITHUB_OUTPUT:
c:\temp\githuboutput\
An error occurred when executing task 'Version'.
Error: Die Syntax für den Dateinamen, Verzeichnisnamen oder die Datenträgerbezeichnung ist falsch. : 'c:\temp\githuboutput\'
```

It looks like the following line occured the error: `build.cake`
`36: System.IO.File.WriteAllText(System.Environment.GetEnvironmentVariable("GITHUB_OUTPUT") ?? System.IO.Path.Combine(System.IO.Path.GetFullPath(outputDir), "semver.txt"), "Version_Info_SemVer=" + versionInfo.SemVer, Encoding.UTF8);`

The directory `c:\temp\githuboutput\` does not exists. 

The run was with an clean checkout of the pull request.

**Comment by Havagan** [comment]
I added a CreateDirectory call to ensure the directory exists.

**Review by mjauernig — APPROVED** [review]

**Comment by mjauernig** [comment]
Local build is ok. But now the step `Cake Build` on github actions fails.
.
image

**Comment by Havagan** [comment]
Oversight on my part -- added a directory exists check before trying to create the directory.

**Comment by mjauernig** [comment]
Still fails. But i did not understand, why the exists-check not working.

Maybee you have to check if script runs local or on github. If on local then create directory. If on github then skip directory creation.

```
ENV:GITHUB_OUTPUT:
D:\a\_temp\_runner_file_commands\set_output_ea52f7b5-5087-4e75-8336-69f3375e782f
SemVer:Output_Dir:
D:\a\_temp\_runner_file_commands\set_output_ea52f7b5-5087-4e75-8336-69f3375e782f
Error: Cannot create 'D:\a\_temp\_runner_file_commands\set_output_ea52f7b5-5087-4e75-8336-69f3375e782f' because a file or directory with the same name already exists.
Error: Process completed with exit code 1.
```

**Comment by Havagan** [comment]
@mjauernig Looking at the history of the cake build and the use of GITHUB_OUTPUT was only added in 2022 to write the semver json to file (semver.txt).

Is this file used anywhere? 

If the write json to file step is failing can we just remove it if the output text file isn't used anywhere else in the CI pipeline?

**Comment by mjauernig** [comment]
> @mjauernig Looking at the history of the cake build and the use of GITHUB_OUTPUT was only added in 2022 to write the semver json to file (semver.txt).
> 
> Is this file used anywhere?
> 
I'm not familiar with cake script. But i looks like, that the content `Version_Info_SemVer=` of the semver.txt file is used here 
`steps.cake-build.outputs.Version_Info_SemVer`
https://github.com/DbUp/DbUp/blob/9a084b4d186618c11327f6104929cfb636fe13cc/.github/workflows/create-draft-release.yml#L52

**Comment by Havagan** [comment]
@mjauernig 

I was too focused on the [test-code.yaml](https://github.com/DbUp/DbUp/blob/master/.github/workflows/test-code.yml), thanks. 

I believe that I understand the cake steps now as used by the [create-draft-release.yml](https://github.com/DbUp/DbUp/blob/master/.github/workflows/create-draft-release.yml).

The `cake-build` step writes the name/value pair "Version_Info_SemVer=versionInfo.SemVer" to the "environment file" identified by the `GITHUB_OUTPUT` environment variable.

- [Environment files](https://docs.github.com/en/actions/using-workflows/workflow-commands-for-github-actions#environment-files)
- [Default environment variables](https://docs.github.com/en/actions/learn-github-actions/variables#default-environment-variables)

The directory that I was trying to delete/create (`D:\a\_temp\_runner_file_commands\set_output_ea52f7b5-5087-4e75-8336-69f3375e782f`) isn't a directory at all, it's a file containing the name/value pairs written to by the cake-build step.

I'll revert the cake.build to only write the semver name/value pair in the GitHub action.

**Comment by droyad** [comment]
Obsoleted by #783

**Pull request closed without merging**
