### PR TITLE
Code cleanup and fix log messages for Firebird, MySql and SqlServer exceptions

### PR DESCRIPTION
**Pull request by sungam3r**
formatting
expression bodies
more ArgumentNullException checks
fix log message for Firebird, MySql and SqlServer exception
fix comments

### CODE REVIEW

**Comment by droyad** [comment]
How did you run the cleanup? It might be easiest for me to replicate that and then do the review of what's left over

**Comment by sungam3r** [comment]
I did everything manually. For a long time, we have a need on our projects to understand how DbUP works. We have several dozen microservices and almost everyone has their own database (SqlServer / Oracle).

So when there was free time I just opened the source code and began to read file by file. In the course of reading, I corrected all the blots found. Behind this, there will be several other changes to the functionality. I just wanted to make PR with all the cosmetic changes first.

**Comment by sungam3r** [comment]
I apologize for the huge PR. The following will solve each their own local problem.

**Comment by sungam3r** [comment]
Any chances to merge this or I will have to split PR into smaller ones?

**Comment by sungam3r** [comment]
@droyad Any chances to merge this?

**Comment by droyad** [comment]
I don't think I'll merge it as is, there is a lot there and it doesn't all fit the desired style (our fault for not defining it correctly).

I will however apply the style changes to `master` and then go through it and cherry pick the non-style changes.

**Comment by sungam3r** [comment]
I can split this PR into small simple parts.

**Comment by AdrianJSClark** [comment]
For the code formatting we should consider adding a `.editorconfig` with our preferred style rules so everyone has the ability to apply things equally.

Obviously this only applies to the style elements of this PR, the other changes would be valid on their own.

I'm happy to put a PR up for this unless someone else beats me to it.

**Comment by sungam3r** [comment]
@droyad @AdrianJSClark I resolved all conflicts and put usings in order. With the latest changes from #434  there are 20 less changed files in this PR. I hope you find time to watch.

**Pull request merged**
