### PR TITLE
Fix to VerifyTableExistsCommand method, lower case tablename fails verify

### PR DESCRIPTION
**Pull request by Timothyoverton**

### CODE REVIEW

**Comment by Timothyoverton** [comment]
Hi All, my PR is failing because of line endings, not sure how to resolve?

**Comment by yufan-at-arcadlon** [comment]
You are using Windows LE while the test is expecting UNIX LE. Git can be configured to automatically translate the LE and make sure only UNIX LE would be committed. You should set `autocrlf` to `true` like this:

    git config --global core.autocrlf true

https://help.github.com/articles/dealing-with-line-endings/

**Comment by sungam3r** [comment]
@Timothyoverton Please rebase onto mastwr if you are still interested.

**Comment by mjauernig** [comment]
Maybe it is already fixed. See #243

**Comment by Jeern** [comment]
@sungam3r  and @mjauernig  Correct. It is fixed (see my comment on #248 )

**Pull request closed without merging**
