### PR TITLE
Added EnsureDatabase.For.PostgresqlDatabase

### PR DESCRIPTION
**Pull request by gertjvr**
this extensions will create the postgresql database if it doesn't exist.

### CODE REVIEW

**Comment by JakeGinnivan** [comment]
The test failure is due to line endings. Leave it with me. I will fix it

**Comment by gertjvr** [comment]
Line endings? thought the approval tests failed.

**Comment by JakeGinnivan** [comment]
Yeah line endings in the approval test :p 

I will switch over to Shouldly for approval tests which ignores line endings by default

**Comment by JakeGinnivan** [comment]
Oh, so it was a legit failure, but it reported line endings different. All good then.

**Comment by JakeGinnivan** [comment]
Will get this released soon

**Comment by gertjvr** [comment]
That was the fastest pr ever... thanks

**Pull request merged**
