### PR TITLE
Fix logs to output formatted values

### PR DESCRIPTION
**Pull request by sungam3r**
Console output
```sql
SELECT 1 as age, 'aaa' as name FROM DUAL
/
```

Before:
```
[13:36:15 INF] ---------------
[13:36:15 INF] | {0, 3} | {1, 5} |
[13:36:16 INF] ---------------
[13:36:16 INF] | {0, 3} | {1, 5} |
[13:36:17 INF] ---------------
[13:36:17 INF]
```

After
```
[13:35:14 INF] ---------------
[13:35:14 INF] | AGE |  NAME |
[13:35:15 INF] ---------------
[13:35:15 INF] |   1 |   aaa |
[13:35:15 INF] ---------------
[13:35:16 INF]
```

### CODE REVIEW

**Comment by Orkad** [comment]
What a good discovery ! i don't even know we can show SELECT result on logs

**Comment by sungam3r** [comment]
ping @AdrianJSClark @droyad

**Comment by sungam3r** [comment]
Ping @droyad @AdrianJSClark and other maintainers.

I offer you my help in supporting this project if you don't have enough time. This does not mean that I will rush to merge all the PRs. I have been supporting [GraphQL.NET](https://github.com/graphql-dotnet/graphql-dotnet) and some other projects for quite some time, and therefore I understand how important it is to review the code. If you are interested, then let me know. In my work I constantly use DbUp and it hurts me to see how this project stagnates.

**Comment by Ekkeir** [comment]
@droyad  @AdrianJSClark , any chance for this PR to be considered?
It seems to be a nice readability improvement.

**Comment by Frost84** [comment]
Just now I've got this trouble and that is a solution!

**Comment by mikelneo** [comment]
I wait this changes for a long time. Will by nice to see this PR merged

**Comment by AdrianJSClark** [comment]
@sungam3r I hope you do not mind but I added a test to ensure that this functionality isn't accidentally broken in the future.

Thanks for fixing this up!

**Comment by sungam3r** [comment]
OK

**Pull request merged**
