### PR TITLE
Updated to Microsoft.Data.SqlClient

### PR DESCRIPTION
**Pull request by chriswill**
Changed Sql.SqlClient to Microsoft.Data.SqlClient.

### CODE REVIEW

**Comment by sungam3r** [comment]
Breaking changes. I am sure that once a similar PR has already been published.

**Comment by sungam3r** [comment]
Yep - https://github.com/DbUp/DbUp/pulls?q=Microsoft.Data.SqlClient

**Comment by chriswill** [comment]
Ok, soooo.  It seems like supporting net3.5 and netstandard1.3 are a higher priority that supporting today's architecture?  It's a breaking change for *those* platforms, but not anyone who is on net4.6 or netstandard2.0.  Which seems like a very large number of people.

I suggested to our company that we use DbUp, but now have run into this issue, which stops us dead in the water.  I can maintain our fork internally, but it seems like it would benefit others.

**Comment by sungam3r** [comment]
I know. I'm not a maintainer of this repo. Just worrying for the slow development of the project.

**Comment by chriswill** [comment]
We can close this PR.  I forked the project and am using this fork in our company's projects.  I changed System.Data.SqlClient there and it works as expected.

@sungam3r you're welcome to contribute to this project any time --> https://github.com/chriswill/DbUpReboot

**Pull request closed without merging**
