### PR TITLE
Fix InvalidCastException on DB existence check (CockhroachDb)

### PR DESCRIPTION
**Pull request by webcoyote**
When checking for the existence of the database, an object is cast to (int?), which works fine for an Int32 object, but crashes on an Int64 object, which is apparently what gets returned when checking CockroachDb, a Postgres-compatible database.

This PR fixes the error by using Convert.Int32 on the object instead of assuming the object type can safely be cast.

Also fixes a duplicate project references error on netstandard1.3

- Remove duplicate project references error
- Fix InvalidCastException on DB existence check

### CODE REVIEW

**Comment by webcoyote** [comment]
This is a pretty straightforward change, but I'm glad to make additional updates if desired. Any chance of getting this merged? Thanks!

**Comment by sungam3r** [comment]
Duplicate project references were fixed in default branch. You may rebase.

**Comment by webcoyote** [comment]
> Duplicate project references were fixed in default branch. You may rebase.

Rebased per request

**Comment by sungam3r** [comment]
@droyad @AdrianJSClark could you please review?

**Review by sungam3r — APPROVED** [review]

**Pull request merged**
