### PR TITLE
Add support for Oracle ManagedDataAcess v12

### PR DESCRIPTION
**Pull request by billydavis**
I forked this in a effort to add Oracle support. I had to update the target framework to support some of the other dependencies; so I'm not real sure what impact that has on some of the other supported databases. The tests for those databases passed; but I'm not sure how extensive those tests are. I look forward to hearing any feedback. Thanks!

### CODE REVIEW

**Comment by droyad** [comment]
Resolves #224

**Comment by thangchung** [comment]
There are couples of conflicts in this PR. Have anyone resolved, verified, and merged it?

**Comment by droyad** [comment]
As discussed on #323 I'm happy to merge this support if it's updated to the 4.0.0 structure. Whoever does do this, ping here first to co-ordinate to prevent duplicate work (any maybe pair).

Once it's done, adding some info on how I can test it (which Oracle DB to install, precanned script and upgrade code snippet) would be much appreciated as then I don't need to learn all the Oracles again that I've long forgotten :).

**Comment by treesrc** [comment]
Hello 
I have forked the master branch and added Oracle support (11g). https://github.com/treesrc/DbUp
Simple Changes in TableJournal class:

1. make EnsureTableExistsAndIsLatestVersion method virtual: Oracle 11 g does not support auto increment id, so I have created a sequence and insert trigger beside schemaversions table.

2. DoesTableExist method body: Oracle returns scalar as a decimal value.

**Comment by droyad** [comment]
@treesrc Awesome, I had a quick look. Could you submit a PR please

**Comment by droyad** [comment]
implemented by #326

**Pull request closed without merging**
