### PR TITLE
Update to Microsoft.Data.SqlClient

### PR DESCRIPTION
**Pull request by johnsimons**
This would be a breaking change.

### CODE REVIEW

**Comment by sungam3r** [comment]
You can use the new package without breaking backward compatibility - it is enough to use preprocessor directives for usings. No need to change the list of target platforms.

**Comment by johnsimons** [comment]
No longer needed, found a different way

**Comment by michaeltnguyen** [comment]
@johnsimons how did you end up doing this?

**Comment by johnsimons** [comment]
Ended up creating https://github.com/OctopusDeploy/Octopus.dbup.SqlServer

**Pull request closed without merging**
