### PR TITLE
Allow custom DB creation script to be passed.

### PR DESCRIPTION
**Pull request by jez9999**
Fixes issue DbUp/dbup-sqlserver#16 - allows custom SQL to be passed to create database.

### CODE REVIEW

**Comment by jez9999** [comment]
Whilst this does change the public API, it does so in a non-breaking way, returning a bool and adding default params that have identical behaviour to before.

**Comment by jez9999** [comment]
"HttpError: Resource not accessible by integration" - no idea why the build failed.  Doesn't seem to be an issue with the code.

**Comment by sungam3r** [comment]
"HttpError: Resource not accessible by integration" is a known issue. But a more serious problem is the level of support for this project 😢 .

**Comment by jez9999** [comment]
Hmm, I've seen worse.  But it's a bit of a shame, as DbUp is a pretty nice way of updating a DB IMHO.

**Comment by jez9999** [comment]
@AdrianJSClark Are you still around on this project?  How about making some more people maintainers?  It does seem like updates have slowed and I think it'd be a shame if the project died.

**Comment by sungam3r** [comment]
> How about making some more people maintainers? It does seem like updates have slowed and I think it'd be a shame if the project died.

Rel: #404

**Comment by Justin-Aurizon** [comment]
I am guessing maybe the build api key has expired?

**Comment by sungam3r** [comment]
Nope. It's a known issue with test reporter. It should be configured properly to work with PRs from forks.

**Comment by jez9999** [comment]
How are they breaking?

**Comment by sungam3r** [comment]
Binary breaking.

**Comment by sungam3r** [comment]
> a non-breaking way, returning a bool and adding default params that have identical behaviour to before.

Your changes are source compatible i.e one need no action to write some new code **but** code is still needed to be recompiled.

**Comment by sungam3r** [comment]
>  If I'm upgrading a library, I'd expect to need to recompile the code.

No. Remember about transitive dependencies. DbUp is library (or package, whatever). It's consumed by apps or other packages. These packages are consumed by some other packages and so on. Your consumers will be unhappy if their app crashes after updating some intermediate lib from v1.0.0 to v1.0.1 or from v1.0.0 to v.1.1.0 because of signatures' changes in that lib.

**Comment by jez9999** [comment]
That's what Nuget is for, the intermediate packages should mark a new required version of the transitive dependency.

**Comment by mjauernig** [comment]
First at all. Thank you @jez9999 for contributing. 

> @jez9999 no, changes are breaking, I suggest to add `develop` branch for v6 and merge all breaking changes there, ping @mjauernig for comments.

I think we should use [Semantic Versioning 2.0.0](https://semver.org/). 
> Major version X (X.y.z | X > 0) MUST be incremented if any backward incompatible changes are introduced to the public 
 API. It MAY also include minor and patch level changes. Patch and minor versions MUST be reset to 0 when major version is  incremented.
 
 So, i would follow @sungam3r and would say we merge it to v6. Because their are a lot of packages which are build on top of [DbUp.Core](https://www.nuget.org/packages?q=dbup). 
 
 I think after we cleaned the ```pull requests``` and ```issues```. We can create a DbUp Version 6 for the existing ```breaking pull requests``` and release them shortly and then go on to v7.

**Comment by jez9999** [comment]
> First at all. Thank you @jez9999 for contributing.
> 
> > @jez9999 no, changes are breaking, I suggest to add `develop` branch for v6 and merge all breaking changes there, ping @mjauernig for comments.
> 
> I think we should use [Semantic Versioning 2.0.0](https://semver.org/).
> 
> > Major version X (X.y.z | X > 0) MUST be incremented if any backward incompatible changes are introduced to the public
> > API. It MAY also include minor and patch level changes. Patch and minor versions MUST be reset to 0 when major version is  incremented.
> 
> So, i would follow @sungam3r and would say we merge it to v6. Because their are a lot of packages which are build on top of [DbUp.Core](https://www.nuget.org/packages?q=dbup).
> 
> I think after we cleaned the `pull requests` and `issues`. We can create a DbUp Version 6 for the existing `breaking pull requests` and release them shortly and then go on to v7.

I still don't get it.  You're using a package manager like Nuget which specifies your dependency tree.  If something requires a newer version of DbUp, the tree should update and you should get the newer version of DbUp.  Who is dropping in a DLL without using a package manager?

**Comment by sungam3r** [comment]
>  Who is dropping in a DLL without using a package manager?

Forget about "dropping dll". The problem of binary incompatibility is well-known one in nuget-driven world of .NET.

Consider dependency graph:

1) Your app -> fancy_package -> some_other_package -> dbup

2) Your_app -> dbup

In your solution you reference/use DbUp explicitly AND use it implicitly (you may not event know about it) through some dependencies.

One day you notice that you **can** update to dbup v1.0.1 from v1.0.0, so... why not?! You bump version to 1.0.1 and 1.0.1 **should not** break anything according to semver. At least you think so (as I and 1000000 more devs). OK. Now think about your changes again and look at fancy_package or some_other_package. They **were compiled** agains DbUp v 1.0.0 some day. You are not the author of these packages. Now at runtime these packages may call APIs from DbUp that do not exist anymore. BOOM! `MethodNotFoundException` here!

https://learn.microsoft.com/en-us/dotnet/core/compatibility/categories#binary-compatibility

**Comment by sungam3r** [comment]
@mjauernig I removed `version6` label, milestones are used for such things.

**Comment by jez9999** [comment]
Hmm, I guess I'm too used to thinking about it from the npm way of doing things where it just downloads multiple versions of the package when they're required by different things.

**Comment by droyad** [comment]
Picked across as https://github.com/DbUp/dbup-sqlserver/pull/20, will go into 6.0

**Pull request closed without merging**
