### PR TITLE
Exposed a new overload to take command timeout

### PR DESCRIPTION
**Pull request by ammaraltahan**
This is a fix for time consuming create database statement especially for Azure dbs.

### CODE REVIEW

**Comment by ammaraltahan** [comment]
OK!! so ... even though I'm a github member for a while, but this is the first time I'm contributing! Please excuse my lack of etiquette and process knowledge.

So I've added an extension method overload that takes command time out as a parameter, but I failed unit tests and I have no idea how to fix it, can you help?

**Comment by JakeGinnivan** [comment]
Hey @ammaraltahan 

Great to have your contribution. I will merge this manually, no worries. One thing which would be good in future is to try and keep to the project formatting. It appears you have tabs instead of spaces which makes formatting in the diff odd. 

Appreciate you resubmitting your original PR as configuration instead :)

**Comment by JakeGinnivan** [comment]
Have cherry picked onto master and release/4.0.0

https://github.com/DbUp/DbUp/commit/2195d303ffa611435c8f8b784432e60242b3a40d and https://github.com/DbUp/DbUp/commit/6c52fde58c26c71bd369cd7c12676d1185550a41

**Comment by ammaraltahan** [comment]
Thanks for your patience, this is my first time doing this, I copied from
vs and pasted in github.

Thanks.
Ammar

**Pull request closed without merging**
