### PR TITLE
Xamarin - iOS Builds for SQLite Only

### PR DESCRIPTION
**Pull request by huntharo**
This is for issue #192

### CODE REVIEW

**Comment by JakeGinnivan** [comment]
Hey

I am actually working on netstandard support for v4 right now in as many of the DB providers as I can, starting with MSSql. Hoping to get a beta out by the weekend. I will push it up tonight and maybe you could add the support there. But at the moment I can't pull this in without redoing pretty much all of the work as I have already converted all the projects.

Thanks and sorry about that

**Comment by huntharo** [comment]
Ok let me take a look. I've been using it in my iOS app and it works great.
Huge fan of DbUp. Been using it for 4 years and got many other teams to use
it. Love it.

**Comment by JakeGinnivan** [comment]
I haven't pushed the branch yet. Will do when I get home tonight

**Comment by JakeGinnivan** [comment]
Hey @huntharo, check out the release/4.0 branch. It has been moved over to project.json and we have initial support for netstandard.

If the release/4.0 branch doesn't exist, it is merged to master so check it out there. Would love a hand improving the SqlLite stuff without adding a heap of extra packages

**Pull request closed without merging**
