### PR TITLE
Case sensitive INFORMATION_SCHEMA table in collations other than Latin

### LINKED ISSUE #170: SqlTableJournal could not find SchemaVersion table if the database collation is not set to Latin*
Hi,
SqlTableJournal could not find SchemaVersion table if the database collation is not set to Latin* because of that DbUp is always executing all scripts.

Solution; the table name( information_schema.tables) must be written upper-case  in the lookup query. https://github.com/DbUp/DbUp/blob/master/src/DbUp/Support/SqlServer/SqlTableJournal.cs#L195-L197
```cs
command.CommandText = string.IsNullOrEmpty(schema)
  ? string.Format("select 1 from information_schema.tables where TABLE_NAME = '{0}'", tableName)
  : string.Format("select 1 from information_schema.tables where TABLE_NAME = '{0}' and TABLE_SCHEMA = '{1}'", tableName, schemaName);
```

### PR DESCRIPTION
**Pull request by omnibs**
This fixes #170

### CODE REVIEW

**Comment by JakeGinnivan** [comment]
Does this issue affect other databases?

In the 4.0 branch I was actually thinking about making this SQL standard for all databases (as information_schema is standard not a SQL server thing I think). I.e moving this down into the Journal base class and then only overriding if needed. Thoughts?

Either way, this fix needs to be applied to both master and release/4.0.0. Either by forward merging master into release/4.0.0 after this is merged or manually.

**Comment by omnibs** [comment]
Possibly, haven't tested. Would require some research.

Seems like a good idea to make it standard, I did google for a standard way to check tables and information_schema is what came out.

I'll handle that on 4.0.0 too.

**Comment by JakeGinnivan** [comment]
What is the status of this?

**Comment by omnibs** [comment]
I hadn't done my homework.

(According to wikipedia)[https://en.wikipedia.org/wiki/Information_schema#Implementation] INFORMATION_SCHEMA is supported by:

* Microsoft SQL Server
* MySQL
* PostgreSQL

And is unsupported by Oracle and Sqlite.

Since Oracle support is still a PR@#77, I believe it's OK to make INFORMATION_SCHEMA an overridable default.

I'm gonna work on this right now and report back by updating the PR.

About 4.0, I'll rewrite the changes on that branch and try to PR to it instead of master, I'm not sure it's possible but a quick google shows it might be.

**Comment by omnibs** [comment]
[Apparently Firebase does not support INFORMATION_SCHEMA](http://www.alberton.info/firebird_sql_meta_info.html#.Vt2NEpwrKUk), so I used these weird tables, but I don't have a Firebird DB to test it.

On the MySql tests I got some different flow going on `src\DbUp.Tests\Support\MySql\MySqlSupportTests.CanHandleDelimiter.approved.`. On your test the Journal table was taken as present, on my test it's taken as nonexistant, so it's creating the table on line 21. Maybe it's more correct like this, since we're simulating an empty DB on the test. What you think?

**Comment by JakeGinnivan** [comment]
> About 4.0, I'll rewrite the changes on that branch and try to PR to it instead of master, I'm not sure it's possible but a quick google shows it might be.

git rebase upstream/release/4.0.0

That will rewrite your history onto the 4.0.0 branch.

**Comment by JakeGinnivan** [comment]
This pr will look quite different on the 4.0 branch. We use schema versions already for most DB's. I think it just needs to be pushed into the base class by default then overriden by the ones that don't support it.

**Pull request merged**
