### PR TITLE
Fix for running dbup on Azure boxes.

### PR DESCRIPTION
**Pull request by ammaraltahan**
I could increase the timeout through a configure like the example in this article "https://phejndorf.wordpress.com/2014/07/02/setting-execution-timeout-in-dbup/" but unfortunately this is not possible for EnsureDatabase.For.SqlServer() method.

### CODE REVIEW

**Comment by JakeGinnivan** [comment]
Could this be made a configuration setting?

**Comment by ammaraltahan** [comment]
Actually I ended up adding an extension method with the same code but with
increased timeout.

As for your question, it is certainly a good solution but requires more
complex changes.

**Comment by JakeGinnivan** [comment]
@ammaraltahan I mean, would you be willing to make this a proper configuration setting to make it easier for others?

**Comment by ammaraltahan** [comment]
Sure!

**Comment by JakeGinnivan** [comment]
Awesome, thanks!

**Comment by JakeGinnivan** [comment]
Superseded by #179

**Pull request closed without merging**
